### ISSUE TITLE
main.js:133 Uncaught TypeError: $(...).scrolly is not a function

### ISSUE THREAD

**Issue by pachadotdev** [andrewbanchich/editorial-jekyll-theme#1]
Hi

I found this issue so that the panel is always on top

```
main.js:133 Uncaught TypeError: $(...).scrolly is not a function
    at HTMLDocument.<anonymous> (main.js:133)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
```

I'll post a fix ASAP

**Comment by pachadotdev** [comment]
solution

go here: https://andrewbanchich.github.io/editorial-jekyll-theme/assets/js/main.js

copy and paste over the code downloaded from the repo :)

**Comment by andrewbanchich** [comment]
@pachamaltese Thanks! Yes, this theme is still in the middle of being converted, so not ready for prime time yet. I should put a notice about that on the repo soon.
